using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using UnityEngine;
using UnityEngine.Networking;
using Newtonsoft.Json;

namespace MedicalExam.RAG
{
    [Serializable]
    internal class RemoteBundleManifest
    {
        public string tenantId;
        public string version;
        public string checksum;
        public int chunkCount;
        public int sourceCount;
        public string publishedAt;
        public string bundlePath;
    }

    [Serializable]
    internal class RemoteBundleManifestEnvelope
    {
        public RemoteBundleManifest manifest;
    }

    /// <summary>
    /// Main interface for RAG (Retrieval Augmented Generation) functionality.
    /// Coordinates between knowledge base, embeddings, and vector database.
    /// </summary>
    public class KnowledgeRetriever : MonoBehaviour
    {
        [Header("Configuration")]
        [SerializeField] private bool autoInitializeWithSampleData = true;
        [SerializeField] private EmbeddingService embeddingService;
        [SerializeField] private string persistentDataPath;

        [Header("Pre-built RAG Database")]
        [Tooltip("Path inside StreamingAssets to the pre-built DB JSON (generated by build_rag_db.py)")]
        [SerializeField] private string prebuiltDbPath = "PrebuiltRAG/medical_knowledge_db.json";

        [Tooltip("If true, always copy the pre-built DB from StreamingAssets on startup (overwrites cached DB).")]
        [SerializeField] private bool syncPrebuiltDbOnStartup = true;

        [Header("Remote Bundle Sync")]
        [Tooltip("If true, try the backend manifest/bundle first, then fall back to local cache.")]
        [SerializeField] private bool syncRemoteBundleOnStartup = false;

        [Tooltip("Backend base URL without trailing slash, e.g. https://my-backend.onrender.com")]
        [SerializeField] private string remoteBackendBaseUrl;

        [Tooltip("Tenant id used by backendlerni manifest and bundle routes")]
        [SerializeField] private string remoteTenantId = "default";

        [Tooltip("Timeout in seconds for remote manifest and bundle HTTP requests")]
        [SerializeField] private int remoteRequestTimeoutSeconds = 20;

        [Header("UI Screens")]
        [Tooltip("Loading screen shown during first-launch RAG initialization")]
        [SerializeField] private GameObject loadingScreen;

        [Tooltip("Main canvas shown after RAG is ready")]
        [SerializeField] private GameObject mainCanvas;

        /// <summary>Fires with a status message during first-launch PDF processing.</summary>
        public event Action<string> OnInitStatusChanged;

        /// <summary>Progress 0-1 during first-launch initialization.</summary>
        public event Action<float> OnInitProgress;

        private VectorDatabase _vectorDatabase;
        private Dictionary<string, KnowledgeChunk> _queryCache = new Dictionary<string, KnowledgeChunk>();
        private const string LocalDatabaseFileName = "medical_knowledge_db.json";
        private const string LocalRemoteManifestFileName = "remote_manifest_cache.json";

        private static KnowledgeRetriever _instance;

        public static KnowledgeRetriever Instance
        {
            get
            {
                if (_instance == null)
                {
                    var go = new GameObject("KnowledgeRetriever");
                    DontDestroyOnLoad(go);
                    _instance = go.AddComponent<KnowledgeRetriever>();
                }
                return _instance;
            }
        }

        public bool IsReady { get; private set; }
        public int KnowledgeChunkCount => _vectorDatabase?.ChunkCount ?? 0;

        private void OnEnable()
        {
            if (_instance == null)
                _instance = this;
        }

        private void Start()
        {
            if (string.IsNullOrWhiteSpace(persistentDataPath))
            {
                persistentDataPath = System.IO.Path.Combine(
                    Application.persistentDataPath,
                    "MedicalRAG"
                );
            }

            _vectorDatabase = new VectorDatabase(persistentDataPath);

            if (embeddingService == null)
            {
                embeddingService = GetComponent<EmbeddingService>();
                if (embeddingService == null)
                {
                    embeddingService = gameObject.AddComponent<EmbeddingService>();
                }
            }

            if (syncRemoteBundleOnStartup && !string.IsNullOrWhiteSpace(remoteBackendBaseUrl))
            {
                if (loadingScreen != null) loadingScreen.SetActive(true);
                if (mainCanvas != null) mainCanvas.SetActive(false);
                StartCoroutine(InitializeWithRemoteOrLocalCoroutine());
                return;
            }

            // Optionally force-sync pre-built DB on every startup so content updates (e.g., CSV case chunks)
            // are reflected without manual cache clearing.
            if (syncPrebuiltDbOnStartup && !string.IsNullOrWhiteSpace(prebuiltDbPath))
            {
                if (loadingScreen != null) loadingScreen.SetActive(true);
                if (mainCanvas != null) mainCanvas.SetActive(false);
                StartCoroutine(CopyPrebuiltDbCoroutine());
                return;
            }

            // Try to load existing database from persistent storage
            if (_vectorDatabase.Load())
            {
                // DB already cached locally — go straight to main canvas
                if (loadingScreen != null) loadingScreen.SetActive(false);
                if (mainCanvas != null) mainCanvas.SetActive(true);

                IsReady = true;
                Debug.Log("[KnowledgeRetriever] Loaded existing knowledge base from local storage");
                _vectorDatabase.PrintStatistics();
                OnInitStatusChanged?.Invoke("Wissensdatenbank geladen");
                OnInitProgress?.Invoke(1f);
            }
            else if (!string.IsNullOrWhiteSpace(prebuiltDbPath))
            {
                // First launch: copy pre-built DB from StreamingAssets → persistent storage
                if (loadingScreen != null) loadingScreen.SetActive(true);
                if (mainCanvas != null) mainCanvas.SetActive(false);
                StartCoroutine(CopyPrebuiltDbCoroutine());
            }
            else if (autoInitializeWithSampleData)
            {
                InitializeWithSampleData();
                SwitchToMainCanvas();
            }
        }

        private IEnumerator InitializeWithRemoteOrLocalCoroutine()
        {
            Debug.Log("[KnowledgeRetriever] Remote-first startup enabled");
            OnInitStatusChanged?.Invoke("Pruefe Online-Wissensdatenbank...");
            OnInitProgress?.Invoke(0.05f);

            bool syncFinished = false;
            bool syncSucceeded = false;
            bool downloadedFreshBundle = false;
            string syncMessage = null;

            yield return TrySyncRemoteBundleCoroutine((success, downloadedFresh, message) =>
            {
                syncSucceeded = success;
                downloadedFreshBundle = downloadedFresh;
                syncMessage = message;
                syncFinished = true;
            });

            yield return new WaitUntil(() => syncFinished);

            if (!string.IsNullOrWhiteSpace(syncMessage))
            {
                Debug.Log(syncSucceeded
                    ? $"[KnowledgeRetriever] {syncMessage}"
                    : $"[KnowledgeRetriever] Remote sync unavailable: {syncMessage}");
            }

            if (_vectorDatabase.Load())
            {
                if (loadingScreen != null) loadingScreen.SetActive(false);
                if (mainCanvas != null) mainCanvas.SetActive(true);

                IsReady = true;
                _queryCache.Clear();

                string statusMessage = downloadedFreshBundle
                    ? "Online-Wissensdatenbank aktualisiert"
                    : "Lokale Wissensdatenbank geladen";

                OnInitStatusChanged?.Invoke(statusMessage);
                OnInitProgress?.Invoke(1f);

                Debug.Log($"[KnowledgeRetriever] Knowledge base ready from {(downloadedFreshBundle ? "remote bundle" : "local cache")}");
                _vectorDatabase.PrintStatistics();
                yield break;
            }

            if (!string.IsNullOrWhiteSpace(prebuiltDbPath))
            {
                yield return CopyPrebuiltDbCoroutine();
                yield break;
            }

            if (autoInitializeWithSampleData)
            {
                InitializeWithSampleData();
                SwitchToMainCanvas();
            }
        }

        /// <summary>
        /// Initializes the knowledge base with sample medical data.
        /// </summary>
        public void InitializeWithSampleData()
        {
            Debug.Log("[KnowledgeRetriever] Initializing with sample medical knowledge...");

            var sampleChunks = MedicalKnowledgeLoader.LoadSampleKnowledge();
            if (sampleChunks.Count == 0)
            {
                Debug.LogError("[KnowledgeRetriever] Failed to load sample knowledge");
                return;
            }

            StartCoroutine(EmbedAndAddChunks(sampleChunks));
        }

        /// <summary>
        /// Loads medical knowledge from a text file and adds it to the database.
        /// </summary>
        public void LoadFromFile(string filePath)
        {
            Debug.Log($"[KnowledgeRetriever] Loading knowledge from {filePath}");

            var chunks = MedicalKnowledgeLoader.LoadFromTextFile(filePath);
            if (chunks.Count == 0)
            {
                Debug.LogError("[KnowledgeRetriever] Failed to load knowledge from file");
                return;
            }

            StartCoroutine(EmbedAndAddChunks(chunks));
        }

        /// <summary>
        /// Uploads a PDF to the external parsing service, embeds the returned chunks,
        /// and adds them to the local vector database.
        /// </summary>
        /// <param name="pdfBytes">Raw PDF file bytes</param>
        /// <param name="filename">Original filename (e.g. "book.pdf")</param>
        /// <param name="category">Optional category (auto-detected if null)</param>
        /// <param name="scenarioTags">Optional comma-separated tags</param>
        /// <param name="onProgress">Progress callback (0-1): 0-0.4 upload, 0.4-0.9 embedding, 0.9-1.0 saving</param>
        /// <param name="onComplete">Called with chunk count on success</param>
        /// <param name="onError">Error callback</param>
        public void LoadFromPdfService(
            byte[] pdfBytes,
            string filename,
            string category = null,
            string scenarioTags = null,
            Action<float> onProgress = null,
            Action<int> onComplete = null,
            Action<string> onError = null)
        {
            var client = FindAnyObjectByType<PdfProcessingClient>();
            if (client == null)
            {
                onError?.Invoke("PdfProcessingClient not found in scene. Add it to a GameObject.");
                return;
            }

            StartCoroutine(LoadFromPdfServiceCoroutine(client, pdfBytes, filename, category, scenarioTags, onProgress, onComplete, onError));
        }

        private IEnumerator LoadFromPdfServiceCoroutine(
            PdfProcessingClient client,
            byte[] pdfBytes,
            string filename,
            string category,
            string scenarioTags,
            Action<float> onProgress,
            Action<int> onComplete,
            Action<string> onError)
        {
            onProgress?.Invoke(0.05f);

            List<KnowledgeChunk> parsedChunks = null;
            string parseError = null;
            bool parseDone = false;

            yield return client.ParsePdf(
                pdfBytes, filename, category, scenarioTags,
                (chunks, metadata) => { parsedChunks = chunks; parseDone = true; },
                (error) => { parseError = error; parseDone = true; }
            );

            yield return new WaitUntil(() => parseDone);

            if (parsedChunks == null || parsedChunks.Count == 0)
            {
                onError?.Invoke(parseError ?? "PDF service returned no chunks");
                yield break;
            }

            onProgress?.Invoke(0.4f);
            Debug.Log($"[KnowledgeRetriever] PDF parsed: {parsedChunks.Count} chunks. Embedding...");

            // Embed all chunks
            var textsToEmbed = new List<string>();
            foreach (var chunk in parsedChunks)
                textsToEmbed.Add(chunk.Content);

            bool embeddingComplete = false;
            List<float[]> embeddings = null;
            string embeddingError = null;

            yield return embeddingService.GetEmbeddingsBatch(
                textsToEmbed,
                (results) => { embeddings = results; embeddingComplete = true; },
                (error) => { embeddingError = error; embeddingComplete = true; }
            );

            yield return new WaitUntil(() => embeddingComplete);

            if (embeddings == null || embeddings.Count == 0)
            {
                onError?.Invoke($"Embedding failed: {embeddingError}");
                yield break;
            }

            onProgress?.Invoke(0.9f);

            for (int i = 0; i < parsedChunks.Count && i < embeddings.Count; i++)
                parsedChunks[i].Embedding = embeddings[i];

            _vectorDatabase.AddChunks(parsedChunks);
            _vectorDatabase.Save();

            IsReady = true;
            onProgress?.Invoke(1.0f);

            Debug.Log($"[KnowledgeRetriever] PDF knowledge loaded: {parsedChunks.Count} chunks embedded and saved");
            _vectorDatabase.PrintStatistics();

            onComplete?.Invoke(parsedChunks.Count);
        }

        /// <summary>
        /// Copies the pre-built RAG database from StreamingAssets to persistent storage on first launch.
        /// No network calls, no PDF processing — just a file copy.
        /// </summary>
        private IEnumerator CopyPrebuiltDbCoroutine()
        {
            Debug.Log("[KnowledgeRetriever] First launch — copying pre-built RAG database...");
            OnInitStatusChanged?.Invoke("Wissensdatenbank wird geladen...");
            OnInitProgress?.Invoke(0.1f);

            string srcPath = System.IO.Path.Combine(Application.streamingAssetsPath, prebuiltDbPath);

            // On Android/Quest, StreamingAssets are inside the APK — must use UnityWebRequest
            using (var request = UnityWebRequest.Get(srcPath))
            {
                request.timeout = 120;
                yield return request.SendWebRequest();

                if (request.result != UnityWebRequest.Result.Success)
                {
                    Debug.LogError($"[KnowledgeRetriever] Failed to read pre-built DB: {request.error}");
                    OnInitStatusChanged?.Invoke("Fehler beim Laden der Wissensdatenbank");
                    if (autoInitializeWithSampleData)
                        InitializeWithSampleData();
                    SwitchToMainCanvas();
                    yield break;
                }

                OnInitProgress?.Invoke(0.6f);

                // Write to persistent storage so VectorDatabase.Load() finds it next time
                string destDir = persistentDataPath;
                if (!System.IO.Directory.Exists(destDir))
                    System.IO.Directory.CreateDirectory(destDir);

                string destPath = GetLocalDatabasePath();
                System.IO.File.WriteAllBytes(destPath, request.downloadHandler.data);

                float sizeMb = request.downloadHandler.data.Length / (1024f * 1024f);
                Debug.Log($"[KnowledgeRetriever] Pre-built DB copied ({sizeMb:F1} MB) → {destPath}");
            }

            OnInitProgress?.Invoke(0.9f);

            // Now load it through VectorDatabase
            if (_vectorDatabase.Load())
            {
                IsReady = true;
                Debug.Log("[KnowledgeRetriever] Pre-built knowledge base ready!");
                _vectorDatabase.PrintStatistics();
            }
            else
            {
                Debug.LogError("[KnowledgeRetriever] Failed to load copied database");
                if (autoInitializeWithSampleData)
                    InitializeWithSampleData();
            }

            OnInitStatusChanged?.Invoke("Wissensdatenbank bereit!");
            OnInitProgress?.Invoke(1f);
            SwitchToMainCanvas();
        }

        private void SwitchToMainCanvas()
        {
            if (loadingScreen != null) loadingScreen.SetActive(false);
            if (mainCanvas != null) mainCanvas.SetActive(true);
        }

        /// <summary>
        /// Retrieves knowledge relevant to a query.
        /// </summary>
        public void RetrieveKnowledge(
            string queryText,
            List<string> scenarioTags = null,
            int topK = 5,
            System.Action<KnowledgeRetrievalResult> onSuccess = null,
            System.Action<string> onError = null)
        {
            if (!IsReady)
            {
                onError?.Invoke("Knowledge base not initialized");
                return;
            }

            if (string.IsNullOrWhiteSpace(queryText))
            {
                onError?.Invoke("Query text is empty");
                return;
            }

            StartCoroutine(RetrieveKnowledgeCoroutine(queryText, scenarioTags, topK, onSuccess, onError));
        }

        /// <summary>
        /// Retrieves knowledge by scenario tags only (no embedding similarity).
        /// </summary>
        public void RetrieveByScenario(
            List<string> scenarioTags,
            int topK = 10,
            System.Action<KnowledgeRetrievalResult> onSuccess = null,
            System.Action<string> onError = null)
        {
            if (!IsReady)
            {
                onError?.Invoke("Knowledge base not initialized");
                return;
            }

            if (scenarioTags == null || scenarioTags.Count == 0)
            {
                onError?.Invoke("Scenario tags are empty");
                return;
            }

            var result = _vectorDatabase.RetrieveByScenario(scenarioTags, topK);
            onSuccess?.Invoke(result);

            Debug.Log($"[KnowledgeRetriever] Retrieved {result.Chunks.Count} chunks for scenario tags");
        }

        /// <summary>
        /// Gets combined context string from retrieved knowledge.
        /// Ready to inject into system prompts.
        /// </summary>
        public string FormatContextForPrompt(KnowledgeRetrievalResult retrievalResult, string header = "MEDICAL KNOWLEDGE CONTEXT:")
        {
            if (retrievalResult == null || retrievalResult.Chunks.Count == 0)
                return "";

            var lines = new List<string>
            {
                header,
                ""
            };

            foreach (var chunk in retrievalResult.Chunks)
            {
                lines.Add($"[{chunk.Category}] {chunk.SectionTitle}");
                lines.Add($"Relevance: {(chunk.SimilarityScore * 100):F1}%");
                lines.Add(chunk.Content);
                lines.Add("");
            }

            return string.Join("\n", lines);
        }

        // ========== PRIVATE METHODS ==========

        private IEnumerator EmbedAndAddChunks(List<KnowledgeChunk> chunks)
        {
            Debug.Log($"[KnowledgeRetriever] Embedding {chunks.Count} chunks...");

            var textsToEmbed = new List<string>();
            foreach (var chunk in chunks)
            {
                textsToEmbed.Add(chunk.Content);
            }

            bool embeddingComplete = false;
            List<float[]> embeddings = null;
            string embeddingError = null;

            yield return embeddingService.GetEmbeddingsBatch(
                textsToEmbed,
                (results) =>
                {
                    embeddings = results;
                    embeddingComplete = true;
                },
                (error) =>
                {
                    embeddingError = error;
                    embeddingComplete = true;
                }
            );

            yield return new WaitUntil(() => embeddingComplete);

            if (embeddings == null || embeddings.Count == 0)
            {
                Debug.LogError($"[KnowledgeRetriever] Embedding failed: {embeddingError}");
                yield break;
            }

            // Assign embeddings to chunks
            for (int i = 0; i < chunks.Count && i < embeddings.Count; i++)
            {
                chunks[i].Embedding = embeddings[i];
            }

            // Add to database
            _vectorDatabase.AddChunks(chunks);
            _vectorDatabase.Save();

            IsReady = true;

            Debug.Log($"[KnowledgeRetriever] Successfully added {chunks.Count} embedded chunks");
            _vectorDatabase.PrintStatistics();
        }

        private IEnumerator RetrieveKnowledgeCoroutine(
            string queryText,
            List<string> scenarioTags,
            int topK,
            System.Action<KnowledgeRetrievalResult> onSuccess,
            System.Action<string> onError)
        {
            bool embeddingComplete = false;
            float[] queryEmbedding = null;
            string embeddingError = null;

            // Get embedding for query
            yield return embeddingService.GetEmbedding(
                queryText,
                (result) =>
                {
                    queryEmbedding = result;
                    embeddingComplete = true;
                },
                (error) =>
                {
                    embeddingError = error;
                    embeddingComplete = true;
                }
            );

            yield return new WaitUntil(() => embeddingComplete);

            if (queryEmbedding == null)
            {
                onError?.Invoke($"Failed to embed query: {embeddingError}");
                yield break;
            }

            // Create query chunk for similarity calculation
            var queryChunk = new KnowledgeChunk
            {
                Embedding = queryEmbedding,
                SectionTitle = queryText
            };

            // Retrieve similar chunks
            var result = _vectorDatabase.RetrieveSimilar(
                queryChunk,
                topK: topK,
                similarityThreshold: 0.3f,
                scenarioTagFilter: scenarioTags
            );

            onSuccess?.Invoke(result);

            Debug.Log($"[KnowledgeRetriever] Retrieved {result.Chunks.Count} knowledge chunks for query: '{queryText}'");
        }

        private IEnumerator TrySyncRemoteBundleCoroutine(Action<bool, bool, string> onComplete)
        {
            string manifestUrl = BuildRemoteManifestUrl();
            using (var manifestRequest = UnityWebRequest.Get(manifestUrl))
            {
                manifestRequest.timeout = Mathf.Max(5, remoteRequestTimeoutSeconds);
                yield return manifestRequest.SendWebRequest();

                if (manifestRequest.result != UnityWebRequest.Result.Success)
                {
                    onComplete?.Invoke(false, false, $"Manifest request failed: {manifestRequest.error}");
                    yield break;
                }

                RemoteBundleManifestEnvelope manifestEnvelope = null;
                try
                {
                    manifestEnvelope = JsonConvert.DeserializeObject<RemoteBundleManifestEnvelope>(manifestRequest.downloadHandler.text);
                }
                catch (Exception ex)
                {
                    onComplete?.Invoke(false, false, $"Manifest parse failed: {ex.Message}");
                    yield break;
                }

                var manifest = manifestEnvelope?.manifest;
                if (manifest == null || string.IsNullOrWhiteSpace(manifest.version))
                {
                    onComplete?.Invoke(false, false, "Manifest response did not include a valid version");
                    yield break;
                }

                OnInitProgress?.Invoke(0.2f);

                if (IsLocalBundleCurrent(manifest))
                {
                    onComplete?.Invoke(true, false, $"Local bundle already matches remote version {manifest.version}");
                    yield break;
                }

                string bundleUrl = BuildRemoteBundleUrl(manifest.version);
                using (var bundleRequest = UnityWebRequest.Get(bundleUrl))
                {
                    bundleRequest.timeout = Mathf.Max(5, remoteRequestTimeoutSeconds);
                    yield return bundleRequest.SendWebRequest();

                    if (bundleRequest.result != UnityWebRequest.Result.Success)
                    {
                        onComplete?.Invoke(false, false, $"Bundle request failed: {bundleRequest.error}");
                        yield break;
                    }

                    string bundleJson = bundleRequest.downloadHandler.text;
                    string checksum = ComputeSha256(bundleJson);
                    if (!string.IsNullOrWhiteSpace(manifest.checksum) && !string.Equals(checksum, manifest.checksum, StringComparison.OrdinalIgnoreCase))
                    {
                        onComplete?.Invoke(false, false, "Bundle checksum mismatch");
                        yield break;
                    }

                    Directory.CreateDirectory(persistentDataPath);
                    File.WriteAllText(GetLocalDatabasePath(), bundleJson, Encoding.UTF8);
                    SaveCachedRemoteManifest(manifest);

                    OnInitProgress?.Invoke(0.7f);
                    onComplete?.Invoke(true, true, $"Downloaded remote bundle {manifest.version}");
                }
            }
        }

        private string BuildRemoteManifestUrl()
        {
            string baseUrl = remoteBackendBaseUrl.Trim().TrimEnd('/');
            string tenantId = UnityWebRequest.EscapeURL(string.IsNullOrWhiteSpace(remoteTenantId) ? "default" : remoteTenantId.Trim());
            return $"{baseUrl}/api/backendlerni/rag/manifest?tenantId={tenantId}";
        }

        private string BuildRemoteBundleUrl(string version)
        {
            string baseUrl = remoteBackendBaseUrl.Trim().TrimEnd('/');
            string tenantId = UnityWebRequest.EscapeURL(string.IsNullOrWhiteSpace(remoteTenantId) ? "default" : remoteTenantId.Trim());
            string encodedVersion = UnityWebRequest.EscapeURL(version);
            return $"{baseUrl}/api/backendlerni/rag/bundles/{encodedVersion}?tenantId={tenantId}";
        }

        private bool IsLocalBundleCurrent(RemoteBundleManifest remoteManifest)
        {
            if (!File.Exists(GetLocalDatabasePath()))
                return false;

            var cachedManifest = LoadCachedRemoteManifest();
            if (cachedManifest == null)
                return false;

            if (!string.IsNullOrWhiteSpace(remoteManifest.checksum) && !string.IsNullOrWhiteSpace(cachedManifest.checksum))
            {
                return string.Equals(cachedManifest.checksum, remoteManifest.checksum, StringComparison.OrdinalIgnoreCase);
            }

            return string.Equals(cachedManifest.version, remoteManifest.version, StringComparison.OrdinalIgnoreCase);
        }

        private RemoteBundleManifest LoadCachedRemoteManifest()
        {
            string manifestPath = GetLocalRemoteManifestPath();
            if (!File.Exists(manifestPath))
                return null;

            try
            {
                return JsonConvert.DeserializeObject<RemoteBundleManifest>(File.ReadAllText(manifestPath));
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[KnowledgeRetriever] Failed to read cached remote manifest: {ex.Message}");
                return null;
            }
        }

        private void SaveCachedRemoteManifest(RemoteBundleManifest manifest)
        {
            if (manifest == null)
                return;

            Directory.CreateDirectory(persistentDataPath);
            File.WriteAllText(GetLocalRemoteManifestPath(), JsonConvert.SerializeObject(manifest, Formatting.Indented), Encoding.UTF8);
        }

        private string GetLocalDatabasePath()
        {
            return Path.Combine(persistentDataPath, LocalDatabaseFileName);
        }

        private string GetLocalRemoteManifestPath()
        {
            return Path.Combine(persistentDataPath, LocalRemoteManifestFileName);
        }

        private string ComputeSha256(string value)
        {
            using (var sha = SHA256.Create())
            {
                byte[] bytes = Encoding.UTF8.GetBytes(value ?? string.Empty);
                byte[] hash = sha.ComputeHash(bytes);
                var builder = new StringBuilder(hash.Length * 2);
                foreach (byte b in hash)
                    builder.Append(b.ToString("x2"));
                return builder.ToString();
            }
        }

        /// <summary>
        /// Clears all knowledge and resets the database.
        /// </summary>
        public void Reset()
        {
            _vectorDatabase?.Clear();
            IsReady = false;
            _queryCache.Clear();
            Debug.Log("[KnowledgeRetriever] Knowledge base cleared");
        }

        /// <summary>
        /// Returns database statistics.
        /// </summary>
        public void PrintStatistics()
        {
            _vectorDatabase?.PrintStatistics();
        }
    }
}
